### ISSUE TITLE
Model validates usage

### ISSUE THREAD

**Issue by ashoda** [westfieldlabs/datetime_helper#3]
What are your thoughts about changing the usage

**From:**
`validates :updated_at, zulu_time: true`

**To:** _Something along the lines of ..._

`validates :updated_at, datetime_format: :zulu`

I think it would make the gem a bit more flexible in the sense of using the same param to support different formats if we ever add any other date or time based validations in the future

@davesag

**Comment by davesag** [comment]
I'd rather not as that would involve monkey patching ActiveModel.  This way is the standard way all 3rd party validators work. (Feel free to prove me wrong).  Right now this is the 'simplest thing that works'.

**Comment by gingermusketeer** [comment]
@davesag It should be doable using an each validator 

See a custom validator with options used here https://github.com/westfield/store_service/blob/master/app/models/store.rb#L43

This is implemented here https://github.com/westfield/store_service/blob/master/app/validators/text_array_validator.rb

You can access anything passed to the validator through the `options` method that is inherited

**Comment by davesag** [comment]
okay thanks @gingermusketeer I'll take a look.

**Comment by davesag** [comment]
Okay I can see it's easy to do, bit I am not convinced it's the right approach.  being able to go `validates :updated_at, zulu_time: true` is consistent with how other 3rd party validators work and means we can get this released and in use this sprint.
